backend/www/controllers/TurningController.php
<?php

namespace app\controllers;

use Yii;
use app\models\PatientTurning;
use app\models\PatientTurningSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PatientTurningController implements the CRUD actions for PatientTurning model.
 */
class TurningController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all PatientTurning models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PatientTurningSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single PatientTurning model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
//        return $this->render('view', [
//            'model' => $this->findModel($id),
//        ]);
        return $this->renderAjax('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new PatientTurning model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new PatientTurning();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index', 'id' => $model->turning_id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing PatientTurning model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index', 'id' => $model->turning_id]);
        } else {
//            return $this->render('update', [
//                'model' => $model,
//            ]);
            return $this->renderAjax('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing PatientTurning model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the PatientTurning model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return PatientTurning the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = PatientTurning::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/www/views/turning/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\datecontrol\DateControl;
use kartik\datetime\DateTimePicker;

/* @var $this yii\web\View */
/* @var $model app\models\PatientTurning */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="patient-turning-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'P_id')->dropDownList($model->getPatientName()) ?>

    <!-- <?= $form->field($model, 'P_id')->textInput() ?> -->

    <!-- <?= $form->field($model, 'latest_turned')->textInput() ?> -->

    <?= $form->field($model, 'latest_turned')->widget(DateControl::classname(),
      [
          'type'=>DateControl::FORMAT_DATETIME,
          'options' => ['placeholder' => 'Select Turning Date'],
          'ajaxConversion'=>true,
          'language' => 'th',
      ]);
   ?>

    <?= $form->field($model, 'turned_by')->dropDownList($model->getStaffName(),['prompt'=>'Select Staff..'] ) ?>


    <?= $form->field($model, 'position')->textInput(['maxlength' => true]) ?>

    <div class="form-group text-right">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/www/views/turning/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\PatientTurningSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="patient-turning-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'turn_id') ?>

    <?= $form->field($model, 'patient_id') ?>

    <?= $form->field($model, 'latest_turned') ?>

    <?= $form->field($model, 'position') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/www/views/turning/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\PatientTurning */

$this->title = 'Create Patient Turning';
$this->params['breadcrumbs'][] = ['label' => 'Patient Turnings', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="patient-turning-create" style="background:#f8f8f8; padding:20px 20px 20px 20px; border-radius:5px">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/www/views/turning/index.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use yii\widgets\Pjax;
use kartik\mpdf\Pdf;
use kartik\datecontrol\DateControl;
use yii\bootstrap\Modal;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;

$this->title = 'Patient Turnings';
$this->params['breadcrumbs'][] = $this->title;
$this->registerJsFile(
    'https://js.pusher.com/4.1/pusher.min.js',
    ['depends' => [\yii\web\JqueryAsset::className()]]
);
//$this->registerJsFile(Yii::$app->request->baseUrl.'/js/deshario_noti.js',['depends' => [\yii\web\JqueryAsset::className()]]);
//$this->registerJs("
//    $('#modal').modal('show');
//    $('#modalContent').load('update?id=1');
//");
$this->registerJs("
    //Pusher.logToConsole = true;
    var pusher = new Pusher('6d49c0fafb127faf5241', {
      cluster: 'ap1',
      encrypted: true
    });
    
    var channel = pusher.subscribe('my-channel'); 
    
    channel.bind('my-event', function(data) {
     var myid = parseInt(data.message);
     $('#modal').modal('show')
     $('#modalContent').load('update?id='+myid)
    });
    
     channel.bind('line-event', function(data) {
     var msg = data.message;
     $.ajax({
            type: 'POST',
	        url: '../includes/line_manager.php',
	        data: {access: 'granted', message:msg},
	        success:function(html) {
	          console.log('Done'); 
	        } 
	      });
    }); 
");

$this->registerJs("    
$(function(){   
    $('.view_btn').click(function (){ 
        $.get($(this).attr('href'), function(data) {
          $('#modal').modal('show')
          .find('#modalContent').html(data)
       });
       return false;
    }); 
    $('.update_btn').click(function (){
        $.get($(this).attr('href'), function(data) {
          $('#modal').modal('show').find('#modalContent').html(data) 
       });
       return false;
    });
});
");
?>

<?php
$title = "Patient Turning Records";
//$title = "<script>document.getElementByID('yourid').value</script>";
Modal::begin([
    "header" => "<h4 class='modal-title'>".$title."</h4>",
    "id" => "modal",
    "size" => "modal-md",
]);
echo "<div id='modalContent' style='margin-top:-20px; margin-left: -10px; margin-right: -5px; margin-bottom: -10px'></div>";
Modal::end();
?>

<div class="patient-turning-index" style="margin-top: -10px">
    <?php Pjax::begin(); ?>
    <?php
    date_default_timezone_set("Asia/Bangkok");
    $date = date('D, d-M-Y H:i a');
    $pdfHeader = [
        'L' => ['content' => 'Nan Hospital',],
        'C' => ['content' => 'Patient Turning Records',],
        'R' => ['content' => 'Generated : '.$date],
        'line' => false,
    ];

    $pdfFooter = [
        'L' => ['content' => '© Deshario',],
        'C' => ['content' => ''],
        'R' => ['content' => '{PAGENO}','font-style' => 'N'],
        'line' => true,
    ];
    ?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'panel' => [
            'heading'=>'<h3 class="panel-title"><i class="fa fa-file-o"></i>&nbsp; Patient Turning Records</h3>',
            'type' => GridView::TYPE_DEFAULT,
            'before' => 'Hi',
            'before'=>Html::a('<i class="glyphicon glyphicon-plus"></i> Create Records', ['create'], ['class' => 'pull-right btn btn-default', 'style'=>'margin-right:5px']),
            'after' => false,
            'footer'=>false
        ],
        'columns' => [
            ['class' => 'yii\grid\SerialColumn','header'=>'<a>#</a>','headerOptions' => ['class' => 'text-center'],'contentOptions' => ['class' => 'text-center']],
            //'turn_id',
            // 'P_id',
            // 'patient.patient_name',
            ['attribute' => 'P_name','value' => 'patient.patient_name',
                'headerOptions' => ['class' => 'text-center'],
                'contentOptions' => ['class' => 'text-center'],
//                'filter' => ArrayHelper::map(\app\models\PatientInfo::find()->all(), 'patient_id', 'patient_name'),
                'filter' => $searchModel->getPatientName(),
                ],

            ['attribute' => 'P_bed','value' => 'patient.patient_bed','headerOptions' => ['class' => 'text-center'],'contentOptions' => ['class' => 'text-center']], //'contentOptions' => ['class' => 'text-center'],
            // 'latest_turned',
            [
                'attribute'=>'latest_turned',
                'contentOptions' => ['class' => 'text-center'],
                'headerOptions' => ['class' => 'text-center'],
                'format'=>'html',
                'value'=>function($model, $key, $inex, $column){
                    // return $model->latest_turned;
                    return Yii::$app->formatter->asDateTime($model->latest_turned,'medium'); //short,medium,long,full
                    //return Yii::$app->formatter->asDate($model->created_at,'medium');
                },
                'filter' => DateControl::widget([
                    'model' => $searchModel,
                    'attribute' => 'latest_turned',
                    'pluginOptions' => [
                        'autoclose' => true,
                        'format' => 'yyyy-mm-dd',
                    ]
                ]),
            ],
            ['attribute'=>'position','headerOptions' => ['class' => 'text-center'],'contentOptions' => ['class' => 'text-center']],
//            'turned_by',
            ['attribute' => 'S_taff','value' => 'staff.staff_name',
                'headerOptions' => ['class' => 'text-center'],
                'contentOptions' => ['class' => 'text-center'],
                'filter' => $searchModel->getStaffName(),
            ],
//            ['class' => 'kartik\grid\ActionColumn','header'=>'<a>Actions</a>'],
            [
                'class' => 'kartik\grid\ActionColumn',
                'template' => '{view} {update} {delete}',
                'buttons' => [
                    'view' => function ($url, $model) {
                        return Html::a('<i class="glyphicon glyphicon-eye-open"></i>', ['view?id='.$model->turning_id],['id' => 'my_view', 'class' => 'view_btn', 'style'=>'margin-right:2px']);
                    },
                    'update' => function ($url, $model) {
                        return Html::a('<i class="glyphicon glyphicon-pencil"></i>', ['update?id='.$model->turning_id],['id' => 'my_update', 'class' => 'update_btn', 'style'=>'margin-right:2px']);
                    },
//                    'delete' => function ($url, $model) {
//                        $url = Url::to(['turning/delete', 'id' => $model->turning_id]);
//                        return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, [
//                            'title'        => 'delete',
//                            'data-confirm' => Yii::t('yii', 'Are you sure you want to delete this item?'),
//                            'data-method'  => 'post',
//                        ]);
//                    },
                ]
            ],
        ],
        'responsiveWrap' => false,
        'exportConfig' => [
            GridView::EXCEL => [
                'label' => 'Excel',
                // 'icon' => $isFa ? 'file-excel-o' : 'floppy-remove',
                'iconOptions' => ['class' => 'text-success'],
                'showHeader' => true,
                'showPageSummary' => true,
                'showFooter' => true,
                'showCaption' => true,
                'filename' => "Patient Turnings",
                'alertMsg' => 'The EXCEL export file will be generated for download.',
                'options' => ['title' => 'Microsoft Excel 95+'],
                'mime' => 'application/vnd.ms-excel',
                'config' => [
                    'worksheet' => 'ExportWorksheet',
                    'cssFile' => ''
                ]
            ],
            GridView::TEXT => [
                'label' => 'Text',
                'filename' => 'Patient Turnings'
            ],
            GridView::PDF => [
                'label' => 'PDF',
                //  'icon' => $isFa ? 'file-pdf-o' : 'floppy-disk',
                'iconOptions' => ['class' => 'text-danger'],
                'showHeader' => true,
                'showPageSummary' => true,
                'showFooter' => true,
                'showCaption' => true,
                'filename' => 'Patient Turnings',
                'alertMsg' => 'The Patient Turning Records will be generated for download.',
                'options' => ['title' => 'Patient Turnings','author' => 'deshario'],
                'mime' => 'application/pdf',
                //  'cssFile' => '@app/web/css/bootstrap.css',
                'config' => [
                    'methods' => [
                        'SetHeader' => [ ['odd' => $pdfHeader, 'even' => $pdfHeader] ],
                        'SetFooter' => [ ['odd' => $pdfFooter, 'even' => $pdfFooter] ],
                    ],
                    'mode' => Pdf::MODE_CORE,
                    'format' => Pdf::FORMAT_A4,
                    'orientation' => Pdf::ORIENT_PORTRAIT,
                    'destination' => Pdf::DEST_BROWSER,
                ],
            ],
        ],

    ]); ?>
    <?php Pjax::end(); ?></div>

backend/www/views/turning/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\PatientTurning */
$this->title = $model->patient->patient_name; 
$this->params['breadcrumbs'][] = ['label' => 'Patient Turnings', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->patient->patient_name, 'url' => ['view', 'id' => $model->turning_id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="patient-turning-update" style="padding:20px 20px 5px 20px; border-radius:5px">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/www/views/turning/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\PatientTurning */

$this->title = $model->patient->patient_name;
$this->params['breadcrumbs'][] = ['label' => 'Patient Turnings', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="patient-turning-view" style="padding:20px 20px 5px 20px; border-radius:5px">

    <form class="form-horizontal">
        <div class="form-group">
            <label class="col-sm-2 control-label">Name</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="myname" value="<?= $model->patient->patient_name; ?>" readonly="">
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">Bed No</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="mybed" value="<?= $model->patient->patient_bed; ?>" readonly="">
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">Turned</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="mycreated" value="<?= $model->latest_turned; ?>" readonly="">
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">Position</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="mycreated" value="<?= $model->position; ?>" readonly="">
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">Turned By</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="mycreated" value="<?= $model->turned_by; ?>" readonly="">
            </div>
        </div>
    </form>

    <?php /* = DetailView::widget([
        'model' => $model,
        'attributes' => [
            'turning_id',
            'P_id',
            'patient.patient_name',
            'patient.patient_bed',
            'latest_turned:datetime',
            'position',
            'turned_by',
        ],
    ]) */ ?>

</div>